/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: typeof import('./src/components/inputs/Checkbox.vue')['default']
    CollapsibleBox: typeof import('./src/components/layout/CollapsibleBox.vue')['default']
    Hint: typeof import('./src/components/Hint.vue')['default']
    Items: typeof import('./src/components/Items.vue')['default']
    ListInfo: typeof import('./src/components/ListInfo.vue')['default']
    ListPreview: typeof import('./src/components/ListPreview.vue')['default']
    Lists: typeof import('./src/components/Lists.vue')['default']
    NavBar: typeof import('./src/components/layout/NavBar.vue')['default']
    NavLink: typeof import('./src/components/layout/NavLink.vue')['default']
    NewRecordDialog: typeof import('./src/components/NewRecordDialog.vue')['default']
    Range: typeof import('./src/components/inputs/Range.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Run: typeof import('./src/components/Run.vue')['default']
    Runs: typeof import('./src/components/Runs.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    ThemeToggle: typeof import('./src/components/layout/ThemeToggle.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    Toggle: typeof import('./src/components/inputs/Toggle.vue')['default']
    Tooltip: typeof import('./src/components/inputs/Tooltip.vue')['default']
  }
}
