/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppInfoPopUp: typeof import('./src/components/popUps/AppInfoPopUp.vue')['default']
    Checkbox: typeof import('./src/components/inputs/Checkbox.vue')['default']
    CollapsibleBox: typeof import('./src/components/layout/CollapsibleBox.vue')['default']
    ConfirmDialog: typeof import('./src/components/dialogs/ConfirmDialog.vue')['default']
    CustomListCard: typeof import('./src/components/CustomListCard.vue')['default']
    DeleteAllCustomListsDialog: typeof import('./src/components/dialogs/DeleteAllCustomListsDialog.vue')['default']
    DeleteAllPlaythroughsDialog: typeof import('./src/components/dialogs/DeleteAllPlaythroughsDialog.vue')['default']
    DeleteCustomListDialog: typeof import('./src/components/dialogs/DeleteCustomListDialog.vue')['default']
    DeletePlaythroughDialog: typeof import('./src/components/dialogs/DeletePlaythroughDialog.vue')['default']
    HintCard: typeof import('./src/components/HintCard.vue')['default']
    ItemsTable: typeof import('./src/components/ItemsTable.vue')['default']
    ListFilters: typeof import('./src/components/ListFilters.vue')['default']
    ListInfoPopUp: typeof import('./src/components/popUps/ListInfoPopUp.vue')['default']
    ListPreviewCard: typeof import('./src/components/ListPreviewCard.vue')['default']
    ListsList: typeof import('./src/components/ListsList.vue')['default']
    LocaleToggle: typeof import('./src/components/layout/LocaleToggle.vue')['default']
    MobileDropdown: typeof import('./src/components/layout/MobileDropdown.vue')['default']
    NavBar: typeof import('./src/components/layout/NavBar.vue')['default']
    NavLink: typeof import('./src/components/layout/NavLink.vue')['default']
    NewRecordDialog: typeof import('./src/components/dialogs/NewRecordDialog.vue')['default']
    PlaythroughCard: typeof import('./src/components/PlaythroughCard.vue')['default']
    PlaythroughFilters: typeof import('./src/components/PlaythroughFilters.vue')['default']
    PlaythroughsList: typeof import('./src/components/PlaythroughsList.vue')['default']
    PopUp: typeof import('./src/components/popUps/PopUp.vue')['default']
    Range: typeof import('./src/components/inputs/Range.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsCard: typeof import('./src/components/SettingsCard.vue')['default']
    ThemeToggle: typeof import('./src/components/layout/ThemeToggle.vue')['default']
    TimerCard: typeof import('./src/components/TimerCard.vue')['default']
    Toasts: typeof import('./src/components/layout/Toasts.vue')['default']
    Toggle: typeof import('./src/components/inputs/Toggle.vue')['default']
    Tooltip: typeof import('./src/components/inputs/Tooltip.vue')['default']
    UploadCustomListDialog: typeof import('./src/components/dialogs/UploadCustomListDialog.vue')['default']
    UploadHistoryJsonDialog: typeof import('./src/components/dialogs/UploadHistoryJsonDialog.vue')['default']
  }
}
