/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/favorites': RouteRecordInfo<'/favorites', '/favorites', Record<never, never>, Record<never, never>>,
    '/history': RouteRecordInfo<'/history', '/history', Record<never, never>, Record<never, never>, '/history/' | '/history/all' | '/history/finished' | '/history/records'>,
    '/history/': RouteRecordInfo<'/history/', '/history', Record<never, never>, Record<never, never>>,
    '/history/all': RouteRecordInfo<'/history/all', '/history/all', Record<never, never>, Record<never, never>>,
    '/history/finished': RouteRecordInfo<'/history/finished', '/history/finished', Record<never, never>, Record<never, never>>,
    '/history/records': RouteRecordInfo<'/history/records', '/history/records', Record<never, never>, Record<never, never>>,
    '/play/': RouteRecordInfo<'/play/', '/play', Record<never, never>, Record<never, never>>,
    '/play/[listId]': RouteRecordInfo<'/play/[listId]', '/play/:listId', { listId: ParamValue<true> }, { listId: ParamValue<false> }>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
  }
}
