---
name: check

on:
  push:
  workflow_dispatch:

jobs:
  format:
    uses: ./.github/workflows/setup-and-run-script.yaml
    with:
      script: 'format'

  lint:
    uses: ./.github/workflows/setup-and-run-script.yaml
    with:
      script: 'lint'

  typecheck:
    uses: ./.github/workflows/setup-and-run-script.yaml
    with:
      script: 'typecheck'

  build:
    uses: ./.github/workflows/setup-and-run-script.yaml
    with:
      script: 'build-only'

  unit-tests:
    uses: ./.github/workflows/setup-and-run-script.yaml
    with:
      script: 'test:unit'
