---
name: setup and run script

on:
  workflow_call:
    inputs:
      script:
        required: true
        type: string

jobs:
  common-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run script
        run: bun run ${{ inputs.script }}
